### ISSUE TITLE
Display price when highlighted on a day

### ISSUE THREAD

**Issue by joshpetit** [lucafluri/price_tracker#53]
**Describe the solution you'd like**
A helpful feature would be displaying a small popup of the price on a specific date when pressed down. This would help when the prices are so close together/high that you can't tell based on the graph. For example:
![Capture+_2020-08-28-14-52-32](https://user-images.githubusercontent.com/59021155/91606148-9037aa00-e93f-11ea-857e-5d0bb34ecd2d.png)
Being able to press on a day and see the price would be really useful

**Describe alternatives you've considered**
Some alternatives would be to have a chart in the menu of a tracked item that details the price on specific days.

keep up the great job guys :)

**Comment by lucafluri** [comment]
@joshpetit This is possible with the current chart package. By long pressing on the chart a popup will appear which can be dragged.

However another issue (#35) exists, which aims to simplify the chart and make it more user friendly
