### ISSUE TITLE
Wrong price in JSON-LD (ld+json) data

### ISSUE THREAD

**Issue by 3id0** [lucafluri/price_tracker#55]
Hey, so I wanted to use Price Tracker with an [Unreal Engine Marketplace URL](https://www.unrealengine.com/marketplace/en-US/product/skeleton-set) but the discount price is ignored in favor of the (higher) base price which makes the tracker pretty much useless for this domain.
So I thought "OK I'll just add unrealengine.com with XPath to `parser_configuration.json` and submit a pull request but ParserXPath actually never gets called in `scraper.dart` because there's a JSON-LD object in the page so ParserSD is called instead of ParserXPath.

**The problem is**: the price attribute in the JSON-LD object on `unrealengine.com/marketplace` is for the base price (which rarely changes), not the discount price (which changes a lot).

**My question**: What would be your advice if I want to add unrealengine.com to the `parser_configuration.json` + ignore the JSON-LD for this domain + submit a pull request?

**Comment by lucafluri** [comment]
Hi thanks for the bug report @3id0.
The scraper favors all structured data over given xpaths. This problem never occured before and it is puzzling me why unity isn't updating their JSON-LD when they have it available.

To fix this case, the priority of the parser has to be changed. The problem now is that several xpaths exist in the configuration and are used as a fallback alternative and would require a lot of manual testing. 

As a temporary fix I would suggest adding a boolean property called "favorXPath" or something to the configuration JSON for each domain and checking this property before using the structured data parser (in scraper.dart).

The parser priority list is then as follows:
1. XPath/Selector if available and favored in configuration
2. Default Structured Data parser
3. Fallback XPath/Selector

This should work without having to test all domains in the configuration manually.
